version: "2"
checks:
  method-lines:
    config:
      threshold: 40
plugins:
  eslint:
    enabled: false
exclude_patterns:
  - ".github/"
  - "config/"
  - "docs/"
  - "test/"
  - "utl/"
  - "**/node_modules/"
  - "**/*.d.ts"
